# Generated by Django 5.2.8 on 2026-05-05 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nexa', '0002_historyentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiotask',
            name='file',
        ),
    ]
