# Generated by Django 5.2.8 on 2026-05-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexa', '0003_remove_audio_file_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyentry',
            name='device_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
